### ISSUE TITLE
RTL suppport

### ISSUE THREAD

**Issue by jayabie** [AgoutiDev/agouti#13]
Hell Team,

Does this software support RTL?
if not, do you have any manual for development purposes.
I'm interested in running a community based on this with RTL support.

**Comment by evgip** [comment]
Until now, there have been no requests to support this mode. Let me see what can be done, how to add it.

**Comment by jayabie** [comment]
I will work on the translation at my free time, once i finish i will pass all the files to your dev email.
i just want to help with this.

**Comment by jayabie** [comment]
Hello @evgip ,

I thought would be better if i share the link with you instead of sending to email.
please the link below for complete Arabic localization.

https://we.tl/t-Mhm386szxZ

the original language file is from September 24th, i don`t know if you guys added new words, but i will check a track them.

**Comment by evgip** [comment]
@jayabie 

Thank you very much! I will check everything and the files will be included in the release. If there are any questions, I will contact you. 

Thanks again!

**Comment by jayabie** [comment]
I did some test on a local environment
i have mirrored the base CSS using the tool below and. added it to `rtl.css`
The tool: https://rtlcss.com/playground/index.html#

Also, i added `dir="rtl"` to the line below.
`<html lang="ar" prefix="og: http://ogp.me/ns# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#" dir="rtl">` 

the mirroring went fine, except the text box couldn`t sent to the right and still doesn't support the mixed characters.

i just did this as a test, i don't know if this will help you by some way as I'm not a coding person myself😉 . 

a screenshot below.

![image](https://user-images.githubusercontent.com/44237013/194130088-3e9afbbf-b12d-4e50-907a-37ec2902aba8.png)

**Comment by evgip** [comment]
@jayabie 

We can add the following code to the editor to enable support:
```
<?php if (Translate::getLang() == 'ar') : ?>direction: 'rtl',<?php endif; ?>
```

I'll look into it. Haven't done it yet, but it's on the roadmap. I plan to support in a future release. Thank you.

**Comment by jayabie** [comment]
Hello @evgip,

This last commit you made above yesterday.
https://github.com/LibArea/libarea/commit/f4cf0b884d5780c55eff2318f0ed1db2bf24604c

sent the website to the right and fixed the mixed characters, but the icons are nested with the text, and the user menu is going out of screen. see the below:
![image](https://user-images.githubusercontent.com/44237013/194385702-2e5697cb-6dfb-45ea-adfd-89b722a73c2d.png)


Like yesterday i have mirrored the base CSS and added to `rtl.css` through my browser console.
the icons nested with the text issue fixed, but the user menu is still going out generating a horizontal scroll bar.
see the below picture after i mirrored the CSS code.
![image](https://user-images.githubusercontent.com/44237013/194386813-7866bb37-f757-4def-9d0f-4320f1ad6ea3.png)


I know you are not focusing on this at this time, but I'm writing this as a reference for the future when you decide to spare the time to achieve RTL. its just part of my test results.

**Comment by evgip** [comment]
@jayabie Thanks a lot. This is a big topic, it should definitely be dealt with in the future.

**Comment by jayabie** [comment]
Hello @evgip,

Is there any possibility i get the access to `libarea/app/Languages/ar/` in this repository?
after i re-installed the version where Arabic is implemented and found that some words need improvement, they are not wrong but as i said needs improvement.
so, i believe having the access that that folder only will make it easy i improve these words without downloading the language folder every time.

if this possible and will not cause any security issues i appreciate if you grant me the access to `ar` folder only, i don`t need access to any other folders as I'm not a coder and i can't help with coding things.

Also, is not necessary i get the access to the folder in this repository if you have any other way i can improve the translation with less work, all is i need to make the localization better and better for this awesome software.

**Comment by evgip** [comment]
@jayabie  

I wanted to contact you about RTL support. Is there any way to contact you other than GitHub?

My email address: `budo@narod.ru`
Or Discord Chat: `https://discord.gg/adJnPEGZZZ`

P.S. I am currently preparing the localization in a separate repository on GitHub to facilitate the work.

**Comment by jayabie** [comment]
Hello @evgip,

Done, i have sent you an email and joined the channel on discord.
you are free to contact me through anyone of these you want.
