### ISSUE TITLE
Адаптивное изображение в ленте

### ISSUE THREAD

**Issue by Dozentz** [AgoutiDev/agouti#15]
Обнаружил криво отображающее изображение в ленте
![Безымянный 137](https://user-images.githubusercontent.com/10892971/191454260-1db88fb6-49bc-47fc-8330-653b9eec13a1.jpg)

**Comment by evgip** [comment]
@Dozentz посмотрите сейчас. Возможно необходимо сделать `Ctrl + F5`, обновить страницу.

**Comment by Dozentz** [comment]
@evgip получше стало, но всё равно края не симметричны
![screen](https://user-images.githubusercontent.com/10892971/191515289-69add8f6-e60d-4fd0-8764-811ded624be1.jpg)

**Comment by evgip** [comment]
Количество вариантов может быть достаточно большое:

* разная ширина экрана;
* пользователь убрал колонку с меню (использует макет из 2 колонок);
* количество изображений, их ширина может быть разной:

![2](https://user-images.githubusercontent.com/6613623/191526408-421dc669-5571-44fd-b688-8f1e8f2146b3.jpg)

Пример, когда участник вывел на центральную 3 изображения и они разной ширины. Думаю, что нам в этом случае необходимо ограничить только допустимый `max-width` параметр.

Надо подумать, можно ли сделать ещё проще. Однако, в любом случае, мы будем работать с разными фото, разной ширины, которые не следует растягиваться на 100% блога. Подача тут информации не совсем такая, как принята на некоторых сайтах, в ленте.
