### ISSUE TITLE
Help with the real meaning of some words

### ISSUE THREAD

**Issue by jayabie** [AgoutiDev/agouti#18]
Hello Team,

I need help with the real meaning with the below words.
in `App.php`

Line#45 "saw" (Do you mean Saw for cutting? one used for cutting wood for example?)
Line#46 "Bodies" (like human bodies?)

**Comment by evgip** [comment]
Line#45 "saw" - from the word: *looked*
Line#46 "Bodies" - this will be removed, but for now you can put a value here: *document body*

**Comment by jayabie** [comment]
Looked = Watched ex: (I saw the post) ?

**Comment by evgip** [comment]
@jayabie There is a conversation not about the post, but the meaning is the same. This is used in the admin panel, on a complaint. Initially, the complaint is highlighted in red. It is necessary to click to deselect (I saw, looked at this complaint) in this vein. In a word.

**Comment by jayabie** [comment]
Hello @evgip 

What is the real meaning for below in `msg.php line 52`
`'silent_mode'           => 'You cannot post content, your account is being verified',`

**Comment by evgip** [comment]
Hello @jayabie 

What happens in this case?
For example, a member with an initial trust level of (TL 1) posts content that falls under the filter. The administration receives a message to view this content (post, reply, comment) and the member's account is switched to silent mode. He is on the site, but cannot take active actions, publish posts, respond ...

Accordingly, we inform  that the participant will no longer be able to publish posts, comments and replies. His account will be verified by the administration.

**Comment by evgip** [comment]
Thank you!
https://github.com/LibArea/libarea/commit/acb6f2e1da82d123d1f6782c767e0d6c292af639
