### ISSUE TITLE
Any plans to add Dislike or voting system up and down?

### ISSUE THREAD

**Issue by jayabie** [AgoutiDev/agouti#20]
Hi team,

I just want to check if you have any plans to add dislike button or up and down votes?
it's very important the users see in which direction the posts are moving? are the people linking them or not?
also, this will help the posts to go up and down in the top tab during a specific time.

Also, this will allow filtering the offensive content, for example a lot of dislikes can lead to the collapse of the post or the comment till the user decides to reveal it.

**Comment by evgip** [comment]
Hello!
There are no plans to add dislikes yet. We have discussed this quite a lot. 
There is a post, there is an answer unfortunately only in Russian.

https://libarea.ru/post/910/o-dizlaykah-i-reputacii-osnovannyh-na-golosovanii-za-i-protiv-na-saytah-predpolagayushchih

P.S. At the moment, the voting system does not work quite flexibly. It will be rewritten soon.
