### ISSUE TITLE
Email SMTP error

### ISSUE THREAD

**Issue by adolfo187** [AgoutiDev/agouti#21]
I have configured the SMTP connection for sending emails in config/integration.php, when I test sending using the administration panel tool, it throws the following error:

`Fatal error: Uncaught Error: Class "SmtpMail\Exception" not found in /home/admin/web/domain.com/public_html/libarea/vendor/ipatov/smtp-mail/src/SendMailSmtpClass.php:84 Stack trace: #0 /home/admin/web/domain.com/public_html/libarea/app/Libraries/SendEmail.php(66): SmtpMail\SendMailSmtpClass->send() #1 /home/admin/web/domain.com/public_html/libarea/app/Libraries/SendEmail.php(52): SendEmail::send() #2 /home/admin/web/domain.com/public_html/libarea/modules/admin/App/Console.php(56): SendEmail::mailText() #3 /home/admin/web/domain.com/public_html/libarea/vendor/phphleb/framework/Constructor/Workspace.php(307): Modules\Admin\App\Console::testMail() #4 /home/admin/web/domain.com/public_html/libarea/vendor/phphleb/framework/Constructor/Workspace.php(120): Hleb\Constructor\Workspace->getController() #5 /home/admin/web/domain.com/public_html/libarea/vendor/phphleb/framework/Constructor/Workspace.php(97): Hleb\Constructor\Workspace->renderGetMethod() #6 /home/admin/web/domain.com/public_html/libarea/vendor/phphleb/framework/Constructor/Workspace.php(34): Hleb\Constructor\Workspace->create() #7 /home/admin/web/domain.com/public_html/libarea/vendor/phphleb/framework/Main/ProjectLoader.php(46): Hleb\Constructor\Workspace->__construct() #8 /home/admin/web/domain.com/public_html/libarea/vendor/phphleb/framework/bootstrap.php(307): Hleb\Main\ProjectLoader::start() #9 /home/admin/web/domain.com/public_html/libarea/public/index.php(26): require('...') #10 {main} thrown in /home/admin/web/domain.com/public_html/libarea/vendor/ipatov/smtp-mail/src/SendMailSmtpClass.php on line 84`

Is there any other point where I should configure the sending of emails?

Thank you!

**Comment by evgip** [comment]
This error indicates that the data written to the `integration.php` file is wrong.

I'm talking about the section:

```
    'smtp'      => true,
    'smtp_user' => 'web@libarea.ru',
    'smtp_pass' => '**************',
    'smtp_host' => 'smtp.yandex.ru',
    'smtp_port' => 465,
```

However, this is an error: `Class "SmtpMail\Exception" not found`

I'll try to fix it, thanks.
