### ISSUE TITLE
EditorJs

### ISSUE THREAD

**Issue by phpuiux** [AgoutiDev/agouti#23]
Понравился движок проекта 👍. Как подключить визуальный редактор EditorJs вместо стандартного? Спасибо

**Comment by phpuiux** [comment]
и сюда немного добавлю - при регистрации появляется ошибка "Protected from CSRF"

**Comment by evgip** [comment]
> и сюда немного добавлю - при регистрации появляется ошибка "Protected from CSRF"

Возможно вы ставите локально? 

В файле `.htaccess`, закомментируйте эти строки, они не нужны:

```
# php_value session.cookie_httponly 1
# php_value session.cookie_secure 1

<IfModule mod_headers.c>
   # Header onsuccess edit Set-Cookie ^(.*) "$1; SameSite=Strict; HttpOnly; Secure"
</IfModule>
```

--- 

По поводу редактора EditorJs. В репозиторий не планируется это пока ставить, т.к. там есть много вопросов. По поводу лицензии, например. Мы будем менять редактор, - однозначно. Но вот когда, сроки, не готов сейчас ответить.
