### ISSUE TITLE
Installation Help 

### ISSUE THREAD

**Issue by uween** [AgoutiDev/agouti#28]
I tried to install this and i'm using cyberpanel and i have made a composer in my public html "composer create-project libarea/libarea . --stability=beta" but the thing is when i open my website using the domain "mydomain.tld or mydomain.tld/public" nothing worked. what is the issue? does any one know how to fix this?

**Comment by acem702** [comment]
You need to program your server to access the index.php from the public folder not the root directory I don't know if a .htaccess file can solve it on cyberpanel

**Comment by uween** [comment]
when i do that there's an error " mydomain.tld is currently unable to handle this request.
HTTP ERROR 500"

**Comment by uween** [comment]
When i Open "mydomain.tld/public" there's an error "mydomain.tld redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS"

**Comment by evgip** [comment]
Look at this post:

https://libarea.ru/post/1359/is-it-possible-to-run-libarea-on-shared-host-through-cpanel

If configured correctly, then you can see: `mydomain.tld/favicon.ico`

Folder `vendor` you can say already built at: `https://libarea.ru/dev/vendor.zip`

**Comment by uween** [comment]
> 

yes i can see the favicon.ico but ui is not loading

**Comment by evgip** [comment]
@uween 

In the `start.hleb.php` file (it's at the root), change this line to true:

```
define('HLEB_PROJECT_DEBUG', true);
```

or look at the logs at: `/storage/logs/`

There must be some errors. If it doesn't work for you.

**Comment by uween** [comment]
> start.hleb.php

thanks to you i solved out the above mentioned problem. thank you so much!. but i got an another problem 

```text
"Fatal error: Uncaught Error: Class "Parsedown" not found in /mydomain/public_html/app/Services/Parser/Filter.php:14 
Stack trace: #0 /mydomain/public_html/app/helpers.php(82): App\Services\Parser\Filter::noHTML()
 
#1 /mydomain/public_html/app/Controllers/Post/PostController.php(54): fragment() 
#2 /mydomain/public_html/vendor/phphleb/framework/Constructor/Workspace.php(307): App\Controllers\Post\PostController->index() 
#3 /mydomain/public_html/vendor/phphleb/framework/Constructor/Workspace.php(120): Hleb\Constructor\Workspace->getController() 
#4 /mydomain/public_html/vendor/phphleb/framework/Constructor/Workspace.php(97): Hleb\Constructor\Workspace->renderGetMethod() 
#5 /mydomain/public_html/vendor/phphleb/framework/Constructor/Workspace.php(34): Hleb\Constructor\Workspace->create() #6 /mydomain/public_html/vendor/phphleb/framework/Main/ProjectLoader.php(46): Hleb\Constructor\Workspace->__construct() #7 /mydomain/public_html/vendor/phphleb/framework/bootstrap.php(325): Hleb\Main\ProjectLoader::start() 
#8 /mydomain/public_html/public/index.php(26): require('...') 
#9 {main} thrown in /mydomain/public_html/app/Services/Parser/Filter.php on line 14"
```

**Comment by evgip** [comment]
What files did you download and how did you even install the script? Did you use the release or download the latest version from the repository?

This error indicates that the versions of the files in the `app` and `vendor` folders are different.

Just download the files that are currently in the repository and add the folder from the archive to them: `https://libarea.ru/dev/vendor.zip`

or, use the composer yourself for assembly.

https://github.com/LibArea/libarea#for-testing-installation

**Comment by evgip** [comment]
@uween 

Did you manage to install? If you have questions, you can write me private messages on the site or in the chat (link at the bottom of the libarea site), I will try to help.

Below is the compiled archive. You can download the script at:

`https://libarea.ru/dev/libarea-0.5.5.zip`

https://libarea.ru/post/1370/add-skript-soobshchestva-libarea-v0-5-5

**Comment by evgip** [comment]
Let's assume the issue is resolved.
