### ISSUE TITLE
font-src CSP violates

### ISSUE THREAD

**Issue by saosangmo** [AgoutiDev/agouti#34]
hi,
When I try post new thing, I get this message:

`Refused to load the font 'https://bangtra.com/assets/js/editor/fonts/ch-icon.woff2' because it violates the following Content Security Policy directive: "font-src https://libarea.ru".`

-Dzung Do

**Comment by evgip** [comment]
Hi!

In the configuration file: `./config/main.php`  In line 171, replace libarea.ru to your domain. It should work out:

```
'font-src' => [
	'https://bangtra.com',
]
```

**Comment by saosangmo** [comment]
Thank evgip so much. It works very well.
