### ISSUE TITLE
Not working on XAMPP

### ISSUE THREAD

**Issue by MESWEB** [AgoutiDev/agouti#4]
WIndows 10
XAMPP
PHP 8.1.2

Browser showing error:

> localhost redirected you too many times.
ERR_TOO_MANY_REDIRECTS

I changed index.php line lines 26 - 27 to this
`define('HLEB_VENDOR_DIR_NAME', '\app\ThirdParty\\');`
`require __DIR__ . '\app\ThirdParty\phphleb\framework\bootstrap.php';` 
and next error is:

> Warning: require_once(C:\xampp\htdocs/default.start.hleb.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\hlew\app\ThirdParty\phphleb\framework\bootstrap.php on line 84
Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs/default.start.hleb.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\hlew\app\ThirdParty\phphleb\framework\bootstrap.php:84 Stack trace: #0 C:\xampp\htdocs\hlew\app\ThirdParty\phphleb\framework\bootstrap.php(88): hleb_require('C:\\xampp\\htdocs...') #1 C:\xampp\htdocs\hlew\index.php(27): require('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\hlew\app\ThirdParty\phphleb\framework\bootstrap.php on line 84

So I give up because I have no time to fix all files and bugs in code for linux servers only

**Comment by evgip** [comment]
I set it to XAMPP,  PHP 8.1.2. The only difference is that it uses win7.
You may have missed the first item for installation in the README.md file:

* Project root folder: public (configure the server )

My file config: httpd-xampp.conf:

```
<VirtualHost *:80>
    ServerAdmin webmaster@lib.loc
        DocumentRoot "d:/xampp/htdocs/lib.loc/public"
        ServerName lib.loc
    ServerAlias www.lib.loc
    ErrorLog "d:/xampp/htdocs/lib.loc/error.log"
        CustomLog "d:/xampp/htdocs/lib.loc/access.log" common
    <Directory "d:/xampp/htdocs/lib.loc/public">
        Require all granted
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost> 
```
File `start.hleb.php`  was returned to the original version...
