### ISSUE TITLE
not website

### ISSUE THREAD

**Issue by joywebpro** [AgoutiDev/agouti#6]
Привет,
Я не могу получить доступ к сайту локально. "Окна"
Вместо этого у меня отображаются все файлы, как я могу увидеть сайт?
![index](https://user-images.githubusercontent.com/96353106/161402453-c2592b77-2aae-4476-b280-0a8ae4fa802d.png)

**Comment by evgip** [comment]
Привет.  
 
Вам необходимо изменить путь в настройках сервера к папке: `public`  (веб-корень Apache).
 
Пример конфигурации для XAMPP, PHP 8.1.2, httpd-xampp.conf:

```
<VirtualHost *:80>
    ServerAdmin webmaster@lib.loc
        DocumentRoot "d:/xampp/htdocs/lib.loc/public"
        ServerName lib.loc
    ServerAlias www.lib.loc
    ErrorLog "d:/xampp/htdocs/lib.loc/error.log"
        CustomLog "d:/xampp/htdocs/lib.loc/access.log" common
    <Directory "d:/xampp/htdocs/lib.loc/public">
        Require all granted
        AllowOverride All
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost> 
```

@joywebpro Возможно этот материал может помочь.

[Почему index.php находится в папке public?](https://libarea.ru/post/737/pocemu-indexphp-nahoditsya-v-papke-public-a-ne-v-obshchey-papke)

**Comment by joywebpro** [comment]
Hello.
In Local php 8.0.13 it's ok ;) I have the website, but when I want to connect: ss@sdf.ru with password, I have "Protected from CSRF" and in "search" this is a blank page.. and online, php 8.1, no website. ...
Online: ovh apache 2.4.
How to config "PUBLIC" online?
AND the French language is bad in local ^^

**Comment by evgip** [comment]
Hello, @joywebpro  

On the local, you need to comment out these 2 lines in the file:  `public/.htaccess`

```php
# php_value session.cookie_httponly 1
# php_value session.cookie_secure 1
```

On live hosting, this will work by default. 

> AND the French language is bad in local ^^

app/Language/fr.php

This needs to be corrected. The translation is not very good and needs to be improved.

**Comment by joywebpro** [comment]
Hello @evgip
So, I don't understand all, in local, when I delete

php_value session.cookie_httponly 1
php_value session.cookie_secure 1
I can connect.

And in my hosting, I always have the folders instead of the website.

**Comment by evgip** [comment]
@joywebpro  Perhaps you should also specify the `public` directory  in the hosting settings, as you did locally. Hosting support usually knows what the conversation is about and I think they can help with it.
