### ISSUE TITLE
English

### ISSUE THREAD

**Issue by ugintl** [AgoutiDev/agouti#8]
Is it available in english?

**Comment by evgip** [comment]
Yes, English is available. For your instance, you can make it the default:

```
'lang'   => 'en',
```
https://github.com/LibArea/libarea/blob/main/config/general.php#L28

Or, after authorization, switch to it in the profile settings:
![English](https://user-images.githubusercontent.com/6613623/186917375-7d966d88-d62b-43ae-af28-c7f568a7e34a.jpg)
